### ISSUE TITLE
competitive-verifier 調べる

### ISSUE THREAD

**Issue by luckylat** [luckylat/library#32]
https://github.com/competitive-verifier/competitive-verifier

**Comment by kzrnm** [comment]
competitive-verifier の作者です。検索から失礼します。

移行手順など宣伝しときます。

## 出力されるもの

https://competitive-verifier.github.io/zzz_luckylat_library/

verification-helper とほぼ同じものが出力されます。

## verification-helper との違い

verification-helper ではできないカスタマイズをできるようにしています。

カスタマイズしない場合の違いは少ないですが、下記のような違いがあります。

- コード部分の表示形式が少し違う
- テストケースが表示される
- 並列実行するので速い

![image](https://github.com/luckylat/library/assets/32071278/d6a5e505-e7a2-4fed-a11e-c241a9bcc1a2)


## 移行手順

### ファイル変更

https://github.com/competitive-verifier/zzz_luckylat_library/commit/7e17c81c724b28a148e334c00c8bd3c9736f4bc9 のコミットの内容で移行可能です

- `.verify-helper` を `.competitive-verifier` に移動
- `timestamps.remote.json` は使わないので削除
- .github/workflows/verify.yml を更新
  - [competitive-verifier の設定ページ](https://competitive-verifier.github.io/competitive-verifier/installer.ja.html?repository=https%3A%2F%2Fgithub.com%2Fcompetitive-verifier%2Fzzz_luckylat_library&parallel=20&tokens=yuki&langs=python%7Cgo%7Chaskel&exclude=ac-library%2F&configToml=.competitive-verifier%2Fconfig.toml) の内容のコピペです

### GitHub Pages の設定

https://github.com/competitive-verifier/zzz_luckylat_library/settings/pages の設定を GitHub Actions に変更する

![image](https://github.com/luckylat/library/assets/32071278/ba792927-76ac-431d-a891-ca315aef62ca)

**Comment by luckylat** [comment]
ありがとうございます。
現状別件で忙しいため後で試してみます。

**Comment by luckylat** [comment]
出来ました！ありがとうございます
